export const LOAD_PATIENT = 'LOAD_PATIENT';
export const PATIENT_SELECTED = 'PATIENT_SELECTED';
export const UPDATE_PATIENT_NAME = 'UPDATE_PATIENT_NAME';
export const LOAD_PATIENT_DEFAULT = 'LOAD_PATIENT_DEFAULT';
